version: '3'
services:
    web:
        image: fe_change
        ports: 
            - "8080:80"
    jobservice: 
        image: job_ch
        ports: 
        - "5000:8082"
        depends_on: 
        - postgres
        - organizationservice
        environment: 
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=1234
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    postgres:
        image: postgres
        environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=postgres
        
    organizationservice: 
        image: org_ch
        ports: 
        - "5001:8081" 
        depends_on:
        - postgres
        environment: 
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=1234
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
                
