FROM node:14

WORKDIR /app
COPY package.json ./
RUN  npm install --legacy-peer-deps
RUN npm install webpack webpack-dev-server webpack-cli json-server

RUN npm run build-dev 

COPY . ./

EXPOSE 9000 3000


CMD ["npm", "start"]
